#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : unixODBC
Version  : 2.3.6
Release  : 1
URL      : http://www.unixodbc.org/unixODBC-2.3.6.tar.gz
Source0  : http://www.unixodbc.org/unixODBC-2.3.6.tar.gz
Summary  : unixODBC is an Open Source ODBC sub-system.
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: unixODBC-bin
Requires: unixODBC-lib
Requires: unixODBC-license
Requires: unixODBC-man
BuildRequires : bison
BuildRequires : flex
BuildRequires : readline-dev

%description
+-------------------------------------------------------------+
| unixODBC                                                    |
+-------------------------------------------------------------+

%package bin
Summary: bin components for the unixODBC package.
Group: Binaries
Requires: unixODBC-license
Requires: unixODBC-man

%description bin
bin components for the unixODBC package.


%package dev
Summary: dev components for the unixODBC package.
Group: Development
Requires: unixODBC-lib
Requires: unixODBC-bin
Provides: unixODBC-devel

%description dev
dev components for the unixODBC package.


%package lib
Summary: lib components for the unixODBC package.
Group: Libraries
Requires: unixODBC-license

%description lib
lib components for the unixODBC package.


%package license
Summary: license components for the unixODBC package.
Group: Default

%description license
license components for the unixODBC package.


%package man
Summary: man components for the unixODBC package.
Group: Default

%description man
man components for the unixODBC package.


%prep
%setup -q -n unixODBC-2.3.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533742075
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1533742075
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/unixODBC
cp exe/COPYING %{buildroot}/usr/share/doc/unixODBC/exe_COPYING
cp libltdl/COPYING.LIB %{buildroot}/usr/share/doc/unixODBC/libltdl_COPYING.LIB
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dltest
/usr/bin/isql
/usr/bin/iusql
/usr/bin/odbc_config
/usr/bin/odbcinst
/usr/bin/slencheck

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libodbc.so
/usr/lib64/libodbccr.so
/usr/lib64/libodbcinst.so
/usr/lib64/pkgconfig/odbc.pc
/usr/lib64/pkgconfig/odbccr.pc
/usr/lib64/pkgconfig/odbcinst.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libodbc.so.2
/usr/lib64/libodbc.so.2.0.0
/usr/lib64/libodbccr.so.2
/usr/lib64/libodbccr.so.2.0.0
/usr/lib64/libodbcinst.so.2
/usr/lib64/libodbcinst.so.2.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/unixODBC/exe_COPYING
/usr/share/doc/unixODBC/libltdl_COPYING.LIB

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/dltest.1
/usr/share/man/man1/isql.1
/usr/share/man/man1/iusql.1
/usr/share/man/man1/odbc_config.1
/usr/share/man/man1/odbcinst.1
/usr/share/man/man5/odbc.ini.5
/usr/share/man/man5/odbcinst.ini.5
/usr/share/man/man7/unixODBC.7
